;;; ai-agent-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "ai-agent" "ai-agent.el" (0 0 0 0))
;;; Generated autoloads from ai-agent.el

(autoload 'ai-agent-focus-new-conversation "ai-agent" "\
Toggle the visibility of the sidebar. Return the focused or created buffer." t)

(autoload 'ai-agent-insert-code-defun "ai-agent" "\
Insert the current function as code in the AI agent session at TARGET-BUFFER.

\(fn &optional TARGET-BUFFER)" t)

(autoload 'ai-agent-insert-code-statement "ai-agent" "\
Insert the current statement as code in the AI agent session at TARGET-BUFFER.

\(fn &optional TARGET-BUFFER)" t)

(autoload 'ai-agent-insert-code-buffer "ai-agent" "\
Insert the current buffer as code in the AI agent session at TARGET-BUFFER.

\(fn &optional TARGET-BUFFER)" t)

(register-definition-prefixes "ai-agent" '("ai-agent-"))

;;;***

;;;### (autoloads nil nil ("function-list.el") (0 0 0 0))

;;;***

;;; End of scraped data

(provide 'ai-agent-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ai-agent-autoloads.el ends here
