#+title: TODO items for Emacs AI Agent

- Make it possible to have several 'sessions'. To each of them a buffer like the sidebar buffer corresponds
  - When called interactively, user functions apply only to one main User session
  - except when called in a particular session's buffer. Then it's for that buffer.
  - There's a mark at the end of the session that
- url-request buffers should be deleted when they've been dumped
- The session buffer should have "User:\n", "Assistant:\n" and "Tool:\n" headers prefixing each message. These should be
  font-locked to particular colors. Names and colors customizable.
  - The session buffer is in org-mode.
- user can freely edit the session, and call an "agent-interact" function. The agent then responds with text and/or tool
  use. Tools are just Emacs Lisp calls wrapped in a #+begin_src tool-use ... #+end_src
  - Since Agents can access all Emacs Lisp functions, they can also freely edit the buffer, and call themselves recursively
  - All interactions are logged to a particular user directory.

- Files or buffers can be included in the conversation. They get included with line-numbers. Agents can edit the file (or buffer) by the command "replace lines 11 to 20", "Add at line 15", "Delete lines 2-30".
  - LLMs probably find it easiest to replace large chunks. Put that in the prompt.
